"""
LeafScan — Evidence Report Generator
Creates structured, evidence-backed vulnerability reports
"""
import json
import os
from datetime import datetime
from pathlib import Path

CVSS_BASE = {
    "critical": 9.5,
    "high":     8.0,
    "medium":   5.5,
    "low":      3.0,
    "info":     0.0,
}

CVSS_VECTOR = {
    "critical": "AV:N/AC:L/PR:N/UI:N/S:C/C:H/I:H/A:H",
    "high":     "AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:N",
    "medium":   "AV:N/AC:H/PR:N/UI:R/S:U/C:L/I:L/A:N",
    "low":      "AV:N/AC:H/PR:L/UI:R/S:U/C:L/I:N/A:N",
    "info":     "AV:N/AC:H/PR:H/UI:R/S:U/C:N/I:N/A:N",
}

def generate_report_id():
    return f"LS-{datetime.now().strftime('%Y%m%d-%H%M%S')}"

def build_finding_md(f, idx):
    sev  = f.get("severity","info").upper()
    cvss = CVSS_BASE.get(f.get("severity","info"), 0.0)
    vec  = CVSS_VECTOR.get(f.get("severity","info"), "")
    return f"""
## Finding #{idx}: {f.get('title','Untitled')}

| Field | Value |
|---|---|
| **Severity** | `{sev}` |
| **Type** | {f.get('vuln_type','Unknown')} |
| **CVSS 3.1 Score** | {cvss} (`{vec}`) |
| **URL** | `{f.get('url','')}` |

### Description
{f.get('description', 'No description.')}

### Steps to Reproduce
{f.get('steps', 'No steps provided.')}

### Proof of Concept
```
{f.get('poc', 'N/A')}
```

### Evidence
```
{f.get('evidence', 'No evidence captured.')}
```

### Impact
{f.get('impact', 'No impact description.')}

---
"""

def generate_markdown_report(target, findings, scan_duration, profile, config=None):
    """Generate a full markdown report with all findings and evidence"""
    from leafscan import __version__, __author__, __company__, __github__

    report_id = generate_report_id()
    now       = datetime.now().strftime("%Y-%m-%d %H:%M:%S UTC")

    summary = {s: 0 for s in ("critical","high","medium","low","info")}
    for f in findings:
        sev = f.get("severity","info").lower()
        if sev in summary:
            summary[sev] += 1

    # Header
    md = f"""# LeafScan Security Report
**Report ID:** `{report_id}`  
**Target:** `{target}`  
**Generated:** {now}  
**Scanner:** LeafScan v{__version__} by {__author__} ({__company__})  
**GitHub:** {__github__}  
**Duration:** {scan_duration:.1f}s · **Profile:** {profile}  

---

## Executive Summary

| Severity | Count |
|---|---|
| 🔴 Critical | {summary['critical']} |
| 🟠 High | {summary['high']} |
| 🟡 Medium | {summary['medium']} |
| 🔵 Low | {summary['low']} |
| ⚪ Info | {summary['info']} |
| **Total** | **{len(findings)}** |

"""

    if not findings:
        md += "> ✅ **No vulnerabilities detected.** The target appears secure against all tested attack vectors.\n"
    else:
        md += "---\n\n## Detailed Findings\n"
        for i, f in enumerate(findings, 1):
            md += build_finding_md(f, i)

    md += f"""
---

## Disclaimer
> This report was generated by LeafScan for authorized security testing only.  
> Unauthorized testing is illegal. Always obtain written permission before scanning.  
>  
> **LeafScan** is an open-source tool by Leaf Security AI, JJ Groups of Company.  
> Built by A.P.Jovin · MIT License · {__github__}
"""
    return report_id, md

def save_report(target, findings, scan_duration, profile, config=None):
    """Save both JSON and Markdown reports, return paths"""
    from leafscan.core.config import REPORTS_DIR, FINDINGS_DIR
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    FINDINGS_DIR.mkdir(parents=True, exist_ok=True)

    report_id, md = generate_markdown_report(target, findings, scan_duration, profile, config)
    safe_target   = target.replace("https://","").replace("http://","").replace("/","_").replace(":","_")
    ts            = datetime.now().strftime("%Y%m%d_%H%M%S")
    base          = f"{safe_target}_{ts}"

    # Save markdown
    md_path   = REPORTS_DIR / f"{base}.md"
    with open(md_path, "w") as f:
        f.write(md)

    # Save JSON
    json_path = FINDINGS_DIR / f"{base}.json"
    with open(json_path, "w") as f:
        from leafscan import __version__, __author__
        json.dump({
            "report_id":       report_id,
            "target":          target,
            "scan_time":       datetime.now().isoformat(),
            "duration_seconds":round(scan_duration, 2),
            "profile":         profile,
            "scanner_version": __version__,
            "scanner_author":  __author__,
            "findings":        findings,
            "summary":         {s: 0 for s in ("critical","high","medium","low","info")},
        }, f, indent=2)

    return report_id, md_path, json_path

def list_reports():
    from leafscan.core.config import REPORTS_DIR
    if not REPORTS_DIR.exists():
        return []
    reports = []
    for f in sorted(REPORTS_DIR.glob("*.md"), reverse=True):
        stat = f.stat()
        reports.append({
            "file": f,
            "name": f.stem,
            "size": stat.st_size,
            "mtime": datetime.fromtimestamp(stat.st_mtime),
        })
    return reports

def ai_classify_finding(finding, config):
    """Use AI to classify a finding and add CVSS score, write-up template"""
    if not config.get("ai", {}).get("enabled"):
        return finding

    try:
        from leafscan.core.ai_client import AIClient
        ai = AIClient(config)
        prompt = f"""You are a senior bug bounty security researcher. 
Analyze this vulnerability finding and respond with a JSON object:
{{
  "severity": "critical|high|medium|low|info",
  "cvss_score": <float>,
  "write_up_template": "<markdown template for bug report>",
  "recommendations": "<fix recommendations>"
}}

Finding:
Title: {finding.get('title')}
Type: {finding.get('vuln_type')}
URL: {finding.get('url')}
Evidence: {finding.get('evidence','')}
"""
        content = ai.call_ai(prompt, "You are a professional security advisor.")
        import re
        json_match = re.search(r'\{.*\}', content, re.DOTALL)
        if json_match:
            ai_data = json.loads(json_match.group())
            finding["ai_severity"]       = ai_data.get("severity", finding.get("severity", "info"))
            finding["ai_cvss"]           = ai_data.get("cvss_score", CVSS_BASE.get(finding.get("severity", "info"), 0))
            finding["ai_writeup"]        = ai_data.get("write_up_template", "")
            finding["ai_recommendations"]= ai_data.get("recommendations", "")
    except Exception:
        pass
    return finding
